#!/bin/bash

set -e

echo Generating runner schema
ts-json-schema-generator --path src/index.ts --type RequestInput --out schema/runner.json

echo Generating compressed runner schema
ts-json-schema-generator --path src/index.ts --type CompressedRequestInput --out schema/runner-compressed.json

echo Generating input schema
ts-json-schema-generator --path src/input.ts --type ModelInput --out schema/input.json

echo Generating output schema
ts-json-schema-generator --path src/output.ts --type ModelOutput --out schema/output.json

echo Generating common input schema
ts-json-schema-generator --path src/input-common.ts --type CommonModelInput --out schema/input-common.json
wetzel schema/input-common.json -w > docs/input-common.md
strip-json-comments --no-whitespace docs/input-common-annotated.json > docs/input-common-example.json
ajv validate -s schema/input-common.json -d docs/input-common-example.json

echo Generating common output schema
ts-json-schema-generator --path src/output-common.ts --type CommonModelOutput --out schema/output-common.json
wetzel schema/output-common.json -w > docs/output-common.md
strip-json-comments --no-whitespace docs/output-common-annotated.json > docs/output-common-example.json
ajv validate -s schema/output-common.json -d docs/output-common-example.json

echo Generating minimal input schema
ts-json-schema-generator --path src/input-minimal.ts --type MinimalModelInputBatch --out schema/input-minimal.json
wetzel schema/input-minimal.json -w > docs/input-minimal.md

echo Generating minimal output schema
ts-json-schema-generator --path src/output-minimal.ts --type MinimalModelOutputBatch --out schema/output-minimal.json
wetzel schema/output-minimal.json -w > docs/output-minimal.md

echo Generating MicroMoB input schema
ts-json-schema-generator --path src/input-MicroMoB.ts --type MicroMoBBHRMInputBatch --out schema/input-MicroMoB.json
wetzel schema/input-MicroMoB.json -w > docs/input-MicroMoB.md

echo Generating MicroMoB output schema
ts-json-schema-generator --path src/output-MicroMoB.ts --type MicroMoBBHRMOutputBatch --out schema/output-MicroMoB.json
wetzel schema/output-MicroMoB.json -w > docs/output-MicroMoB.md
